export enum FrontendErrorCodes {
    CAPTCHA_FAILED = 'CAPTCHA_FAILED',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
    VERIFICATION_TOKEN_DOES_NOT_EXIST = 'VERIFICATION_TOKEN_DOES_NOT_EXIST',
    VERIFICATION_TOKEN_HAS_EXPIRED = 'VERIFICATION_TOKEN_HAS_EXPIRED',
    ACCOUNT_ALREADY_VERIFIED = 'ACCOUNT_ALREADY_VERIFIED',
    WRONG_USERNAME_OR_PASSWORD = 'WRONG_USERNAME_OR_PASSWORD',
    ACCOUNT_IS_INACTIVE = 'ACCOUNT_IS_INACTIVE',
    NOT_LOGGED_IN = 'NOT_LOGGED_IN',
}
